### ISSUE TITLE
Apply Salary Failed to Adjust Pursers' Salary

### ISSUE THREAD

**Issue by BenZeero** [ZoeBijl/airlinesim-enhancement-suite#57]
After applying the new salary, pursers' salary is not adjusted. 
No issue found in the extension page, reinstall the extension did not fix the problem.

**Comment by BenZeero** [comment]
It seems like the issue fixed itself after a second reinstall and restart the browser. 
Unable to reproduce the error found.

**Comment by ZoeBijl** [comment]
Thank you for the issue report and for closing it. Do let me know if it happens again!
