### ISSUE TITLE
general notifications / messages area

### ISSUE THREAD

**Issue by ZoeBijl** [ZoeBijl/airlinesim-enhancement-suite#62]
A general notifications / messages area would be helpful. This could be used for messages / updates about the AES system. Things like “updating prices” / “details updated”.

Maybe the chrome extension “messages” function can be used for this.

**Comment by RobertFridolin** [comment]
Something like ASX has? Then maybe this can be used together, not every extension has to have its own notification area?

**Comment by ZoeBijl** [comment]
I would like to integrate it a bit better into the AS UI. Preferably using their own message/notification style.
