### ISSUE TITLE
Aircraft profitability issues

### ISSUE THREAD

**Issue by SoClownish** [ZoeBijl/airlinesim-enhancement-suite#69]
![image](https://github.com/ZoeBijl/airlinesim-enhancement-suite/assets/101531647/7c8865c8-7e07-4acb-9f89-056b78eac5d9)

When using the aircraft profitability drop down, there continues to be an error stating "No aircraft data in memory. Open fleet management to extract aircraft data." I have extracted all the route details for every plane at least twice, refreshed the pages, created a new fleet type and nothing seems to work. This has been going on for two days.

**Comment by RobertFridolin** [comment]
I guess problem is this function [fltmng_getAirlineName(){](https://github.com/ZoeBijl/airlinesim-enhancement-suite/blob/bab4282a0399a0d89d4005d715dbac3e31ae3b9e/extension/content_fleetManagement.js#L102) which removes certain characters from the Airline name. Therefore the data here https://github.com/ZoeBijl/airlinesim-enhancement-suite/blob/bab4282a0399a0d89d4005d715dbac3e31ae3b9e/extension/content_dashboard.js#L2113 cannot be found.

**Comment by RobertFridolin** [comment]
so a fix would require to look for the "old style" name at this point in content_dashboard.js with removed special characters from airline name
or 
use the "new style" with special characters (should only be additional blanks?) in airline name also also at this point in content_fleetManagement.js in future and patch old data to new format

**Comment by RobertFridolin** [comment]
the airline name filtering used currently in parts of AES could also lead to a collision if someone uses the normal name and the filtered name in another airline

the second solution should therefore be implemented in the longer term

**Comment by ZoeBijl** [comment]
> which removes certain characters from the Airline name

Oh interesting. this is why the AES helper class is so important; as long as everything uses the same pattern to sanitise data it should be alright. Nice digging!

> so a fix would require to look for the "old style" name

Can you elaborate, what would that look like?

**Comment by RobertFridolin** [comment]
> Can you elaborate, what would that look like?

    let key = server + airline.name + 'aircraftFleet';

goes to

    let key = server + airline.name.trim().replace(/[^A-Za-z0-9]/g, '') + 'aircraftFleet';

see above

**Comment by ZoeBijl** [comment]
> > Can you elaborate, what would that look like?
> 
> ```
> let key = server + airline.name + 'aircraftFleet';
> ```
> 
> goes to let key = server + airline.name.trim().replace(/[^A-Za-z0-9]/g, '') + 'aircraftFleet'; see above

~~I rather meant, what would “old style” look like? And what’s new style for that matter? I’m trying to understand what your suggestion is :)~~

ah i see
